function updateNutritionGoals(){const mode=document.getElementById('n-goal-mode')?.value||'maintain';const c=cfg();const calT=getCalTarget(mode);const macros=getMacros(calT,c.tdeeweight||70);['n-cal-target','n-protein-t','n-carb-t','n-fat-t'].forEach((id,i)=>{const el=document.getElementById(id);if(el)el.textContent=[calT,macros.protein,macros.carb,macros.fat][i];});const hintEl=document.getElementById('n-mode-hint');if(hintEl)hintEl.textContent={maintain:'維持: TDEEと同等。筋肉量を保ちながら体組成を安定させます',cut:'減量: TDEE-15%。週0.4〜0.5kg減が目安。タンパク質は高めを維持',bulk:'増量: TDEE+10%。リーンバルクで週0.25〜0.5kg増が目標'}[mode]||'';}

function saveMeal(){const food=document.getElementById('n-food').value;const cal=parseInt(document.getElementById('n-cal').value)||0;if(!food||!cal){alert('食品名とカロリーは必須です');return}DB.push('meals',{date:document.getElementById('n-date').value,meal:document.getElementById('n-meal').value,food,cal,protein:parseInt(document.getElementById('n-protein').value)||0,carb:parseInt(document.getElementById('n-carb').value)||0,fat:parseInt(document.getElementById('n-fat').value)||0,id:Date.now()});['n-food','n-cal','n-protein','n-carb','n-fat'].forEach(id=>document.getElementById(id).value='');renderMealLog();updateNutritionTotals();}

function updateNutritionTotals(){const meals=DB.arr('meals').filter(m=>m.date===today());const cal=meals.reduce((a,m)=>a+(m.cal||0),0),p=meals.reduce((a,m)=>a+(m.protein||0),0),c2=meals.reduce((a,m)=>a+(m.carb||0),0),f=meals.reduce((a,m)=>a+(m.fat||0),0);document.getElementById('n-today-cal').textContent=cal;document.getElementById('n-today-p').textContent=p;document.getElementById('n-today-c').textContent=c2;document.getElementById('n-today-f').textContent=f;const mode=document.getElementById('n-goal-mode')?.value||'maintain';const target=getCalTarget(mode);const rem=target-cal;const remEl=document.getElementById('n-remaining-alert');if(rem>0)remEl.innerHTML=`<div class="alert alert-info">あと <strong>${rem}kcal</strong> 摂取可能（達成率 ${Math.round(cal/target*100)}%）</div>`;else if(rem===0)remEl.innerHTML=`<div class="alert alert-success">目標カロリーに到達しました！</div>`;else remEl.innerHTML=`<div class="alert alert-warn">目標を <strong>${Math.abs(rem)}kcal</strong> オーバーしています</div>`;}

function renderMealLog(){const meals=DB.arr('meals').filter(m=>m.date===today()).reverse();const el=document.getElementById('n-meal-list');if(!meals.length){el.innerHTML='<div class="muted">今日の食事記録がありません</div>';return}el.innerHTML='<table><thead><tr><th>タイミング</th><th>食品</th><th>kcal</th><th>P</th><th>C</th><th>F</th></tr></thead><tbody>'+meals.map(m=>`<tr><td>${mealLabel[m.meal]||m.meal}</td><td style="max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${m.food}</td><td class="mono">${m.cal}</td><td class="mono">${m.protein}g</td><td class="mono">${m.carb}g</td><td class="mono">${m.fat}g</td></tr>`).join('')+'</tbody></table>';}

function updateSmartNutrition(){const c=cfg();const isTr=document.getElementById('today-training')?.checked??true;const bf=parseFloat(document.getElementById('n-bodyfat')?.value)||null;const mode=document.getElementById('n-goal-mode')?.value||c.goalmode||'maintain';let autoMode=mode;let bfAlert=null;if(bf){if(bf>=18){autoMode='cut';bfAlert={t:'alert-danger',m:`体脂肪率${bf}% → ミニカット推奨。`};}else if(bf>=15){autoMode='cut';bfAlert={t:'alert-warn',m:`体脂肪率${bf}% → ミニカット検討ゾーン。`};}else if(bf<=12){bfAlert={t:'alert-success',m:`体脂肪率${bf}% → バルクアップ最適ゾーン。`};}}const baseT=getCalTarget(autoMode);const offCal=isTr?baseT:Math.round(baseT*0.93);const macros=getMacros(offCal,c.tdeeweight||70);const carbT=Math.round(macros.carb*(isTr?1.0:0.80));const fatT=Math.round(macros.fat*(isTr?1.0:1.10));['n-cal-target','n-protein-t','n-carb-t','n-fat-t'].forEach((id,i)=>{const el=document.getElementById(id);if(el)el.textContent=[offCal,macros.protein,carbT,fatT][i];});const w=parseFloat(c.tdeeweight)||70;const tEl=document.getElementById('smart-targets');if(tEl)tEl.innerHTML=`<div class="card-sm"><div class="label">トレ前目安</div><div style="font-size:13px">炭水化物: <strong>${Math.round(w*1.15)}g</strong></div><div style="font-size:13px">タンパク質: <strong>${Math.round(w*0.6)}g</strong></div><div class="muted" style="font-size:11px;margin-top:5px">脂質0〜15g・2〜3h前</div></div><div class="card-sm"><div class="label">トレ後（最重要）</div><div style="font-size:13px">炭水化物: <strong style="color:var(--accent4)">${Math.round(w*2.0)}g</strong></div><div style="font-size:13px">タンパク質: <strong>20g以上</strong></div><div class="muted" style="font-size:11px;margin-top:5px">脂質最小・2h以内</div></div><div class="card-sm"><div class="label">${isTr?'トレ日':'オフ日'}合計</div><div style="font-size:13px">カロリー: <strong>${offCal}kcal</strong></div><div style="font-size:13px">炭水化物: <strong>${carbT}g</strong>${isTr?'':' <span style="font-size:11px;color:var(--accent3)">(-20%)</span>'}</div></div>`;
  const bEl=document.getElementById('smart-badges');if(bEl){const mc={maintain:'badge-blue',cut:'badge-amber',bulk:'badge-green'};const ml={maintain:'維持',cut:'減量',bulk:'増量'};bEl.innerHTML=`<span class="badge ${mc[autoMode]}">${ml[autoMode]}モード</span>${isTr?'<span class="badge badge-blue">トレ日</span>':'<span class="badge badge-gray">オフ日</span>'}`;}
  const aEl=document.getElementById('smart-advice-box');if(aEl&&bfAlert)aEl.innerHTML=`<div class="alert ${bfAlert.t}">${bfAlert.m}</div>`;else if(aEl)aEl.innerHTML='';
  updateNutritionTotals();}